version: '3.1'

services:

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moneyapp
    volumes:
      - ./docker/data:/var/lib/mysql
    expose:
      - 3306
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      timeout: 60s
      interval: 10s
      retries: 10

  server:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_healthy
